### ISSUE TITLE
New version 7.6 of fah-installer doesn't create valid URL for download

### ISSUE THREAD

**Issue by StrangelyPerfect** [microsoft/Windows-Sandbox-Utilities#24]
Today's version, at https://download.foldingathome.org/releases/public/release/fah-installer/windows-10-32bit/ at https://download.foldingathome.org/releases/public/release/fah-installer/windows-10-32bit/v7.6/ isn't parsed correctly.   It creates 7.5999999 or similar on my two machines.

I have modified my local version at Line 43 to include a Rounding to 1d.p.:
$version = ((Invoke-WebRequest -Uri $installer_url -UseBasicParsing).Links | Where-Object  {$_.href -match '^v\d+([.]\d+)?'} | ForEach-Object {[math]::Round([float]($_.href -replace '[^.\d]', ''),1)} | Measure-Object -Max).Maximum 

...which works, but it seems a bit of a kludge to me.

**Comment by le0b** [comment]
Similar problem here:
When I run 'install_folding_sandbox_on_host.ps1' I get the following error:


Checking for latest version of foldingathome...
Invoke-WebRequest : The remote server returned an error: (404) Not Found.
At C:\Temp\install_folding_sandbox_on_host.ps1:48 char:19
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Using FAH v7.59999990463257...

...Invoke-WebRequest : 404 Not Found
nginx/1.14.2
At C:\Temp\install_folding_sandbox_on_host.ps1:59 char:2
+     Invoke-WebRequest -Uri $installer -OutFile "$working_dir\$install ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by brasmith-ms** [comment]
Thank you for pointing this out, just started seeing this myself. I'll get a patch in!

**Comment by brasmith-ms** [comment]
Okay should work now, not sure why I had the float type conversion in there...

Let me know if you're still hitting issues

**Comment by le0b** [comment]
Yep, that fixed it for me, thank you!
