### ISSUE TITLE
how to save Windows SandBox's state?

### ISSUE THREAD

**Issue by HppZ** [microsoft/Windows-Sandbox-Utilities#32]
I use WSB because I want an isolated container, not a clean container every time I launch it.

**Comment by pbozzay** [comment]
Hi,

Right now true persistence isn't supported in Sandbox. For that you can use a virtual machine with checkpoints. Another workaround is to map the data from your host via a mapped folder in the WSB file so that it is hydrated whenever the Sandbox is launched, and combine that with a startup script that installs programs that you need your Sandbox to have.

**Comment by Foadsf** [comment]
Dear Paul @pbozzay could you be kind to at least label this issue as a feature request? Windows Sadnboxes could be a great tool, however, in their state, there is not much use to them. Some software requires a restart after installation. And many tasks might take more than a day and one can't leave a computer always on!

**Comment by roysubs** [comment]
Persistence is now officially supported from Windows 11 build 22509 onwards (I'm not sure of the particulars of how you enable the persistence feature as I don't run Windows 11, but it's been officially stated by Microsoft).

**Comment by roman6078** [comment]
> Persistence is now officially supported from Windows 11 build 22509 onwards (I'm not sure of the particulars of how you enable the persistence feature as I don't run Windows 11, but it's been officially stated by Microsoft).

Do you have any official link /info snippet ?

**Comment by VsevolodGolovanov** [comment]
> Persistence is now officially supported from Windows 11 build 22509 onwards (I'm not sure of the particulars of how you enable the persistence feature as I don't run Windows 11, but it's been officially stated by Microsoft).

Not quite. The documentation states
> Note, however, that as of [Windows 11 Build 22509](https://blogs.windows.com/windows-insider/2021/12/01/announcing-windows-11-insider-preview-build-22509/), your data will persist through a restart initiated from inside the virtualized environment useful for installing applications that require the OS to reboot.

and

> Windows Sandbox now supports reboot inside of its virtualized environment (for example, if you were to click the Restart option under the Power button in Start).

So no, that's not quite what this issue talks about.

**Comment by smokeyhallow** [comment]
Not available for Windows 10?

**Comment by doobes** [comment]
Persistence on a Win10 box would be 'da bomb....

**Comment by laggingreflex** [comment]
As a workaround I was able to persist AppData and got msedge to retain its state:
```xml
    <MappedFolder>
      <HostFolder>D:\Sandbox\AppData</HostFolder>
      <SandboxFolder>C:\Users\WDAGUtilityAccount\AppData</SandboxFolder>
      <ReadOnly>False</ReadOnly>
    </MappedFolder>
```
But it messed up some features and icons. Maybe more stuff can be persisted this way.. I'd try copying the entire drive and select which parts I wanna preserve. Not sure if registry or other such settings would work...

**Comment by valen214** [comment]
> As a workaround I was able to persist AppData and got msedge to retain its state:
> 
> ```
>     <MappedFolder>
>       <HostFolder>D:\Sandbox\AppData</HostFolder>
>       <SandboxFolder>C:\Users\WDAGUtilityAccount\AppData</SandboxFolder>
>       <ReadOnly>False</ReadOnly>
>     </MappedFolder>
> ```
> 
> But it messed up some features and icons. Maybe more stuff can be persisted this way.. I'd try copying the entire drive and select which parts I wanna preserve. Not sure if registry or other such settings would work...

You can first copy the hydrated appdata to the host folder before actually mapping. It solves SOME of the problems.
And exporting the whole (or a part of) registry before turning off the sandbox solves some other problems.

**Comment by Foadsf** [comment]
I must say I’m quite disappointed that after so many years, **Windows 10 users still do not have proper persistence in Windows Sandbox**. This is a huge missed opportunity: a lightweight containerized environment with restart and persistence would have been a game-changer, especially for developers and IT professionals who can’t always move to Windows 11.

Since this feature isn’t coming to Windows 10, a good alternative is [Sandboxie Plus](https://sandboxie-plus.com/). Unlike Windows Sandbox, it does provide persistent containers on Windows 10.

**Comment by detuur** [comment]
I've noticed an undocumented property in .wsb files that hint at some (upcoming?) support for persistence.

Steps to reproduce:
- Open Sandbox directly, not through a .wsb file
- Sandbox will create a `Default.wsb` file, at `AppData\Local\Packages\MicrosoftWindows.WindowsSandbox_cw5n1h2txyewy\LocalState\Recipes\Default.wsb`
- This file contains a line saying `<PersistenceSupport>Disable</PersistenceSupport>`

Now, I can't find any reference to this property anywhere online, or in any documentation. Enabling it does not do anything, as far as I can tell. There's other undocumented properties there as well, some of which are in fact useful, but there's more than one dud. I can only conclude that they've already discussed this internally and that it has at least gotten far enough for them to change the schema of .wsb files.

This may sound pretty exciting for those of us waiting for this feature, but don't get your hopes up too much. This could be years out or may have already been cancelled.

Version details:
- Windows 11 Enterprise 25H2 26200.6584
- Windows Sandbox 0.5.3.0

**Comment by iAmBipinPaul** [comment]
**Please reopen this issue.**

a lightweight, isolated, reproducible, and persistent Windows development environment—similar to Dev Containers, but for Windows‑native GUI apps. Current options don’t meet this need:  
- Dev Containers + WSL 2 only support Linux and cannot run Windows GUI apps.  
- Windows Sandbox is lightweight but not persistent; all tools and configuration are lost on every restart.  
- Full VMs (Hyper‑V/VMware/VirtualBox) are persistent but heavy, slow, and not suitable for quick, reproducible dev environments.  
- Windows containers don’t support general Windows GUI workflows.  

Developers need a clean, isolated Windows environment with fast startup, the ability to install tools (Visual Studio, SDKs, dependencies), and persistence across sessions—something like a “persistent Windows Sandbox” defined by a config file, similar to devcontainer.json.

cc @shanselman

**Comment by iAmBipinPaul** [comment]
In the age of agentic-derived workflows, the need for such an environment is quite important so that an agent can work in an isolated dev environment.

**Comment by silicahd** [comment]
Well i agree with all of you. I just want to separate most of my environments in my computer. Sandbox with ability to create different environments that persist would be gold for Windows how are they not seeing this? 

After doing a crazy amount of digging here is what i found so far. 

  AllowPersistence under AppHVSI PolicyManager is currently value = 0x0 (disabled). The current\device\AppHVSI key
  doesn't even exist yet — nothing has ever set it.

  The native code in hvsicontainerservice.dll calls PolicyManager_GetPolicyInt("AllowPersistencePolicyOn") which
  resolves to this policy. Until it's 1, CreateStorage / CmsCreateStorage will never be called.

  Step 1 — Set the Group Policy registry key (requires elevated shell)

  reg add "HKLM\SOFTWARE\Policies\Microsoft\AppHVSI" /v AllowPersistence /t REG_DWORD /d 1 /f
  This is what PolicyManager reads for the AppHVSI\AllowPersistence policy (confirmed via
  grouppolicypath/grouppolicyname in the registry metadata). It overrides the default 0x0.

  Step 2 — Create your storage directory (This directory was found in one of the dlls. - so they must have it in there)

  mkdir C:\SandboxStorage

  Step 3 — WSB config (complete, corrected)

  <Configuration>
    <PersistenceSupport>Enable</PersistenceSupport>
    <StorageConfiguration>
      <StoragePath>C:\SandboxStorage</StoragePath>
      <DiskSizeInMB>20480</DiskSizeInMB>
    </StorageConfiguration>
  </Configuration>

  Step 4 — Reboot or restart the HVSI container service

  The PolicyManager WNF notification will propagate, but a reboot is safest:
  net stop hvsicontainerservice 2>nul
  net start hvsicontainerservice 2>nul
  Or just reboot.

  What to Watch For

  - After launch, C:\SandboxStorage should contain PersistentUserDisk.vhdx or PersistentUserData.vhdx
  - If it fails: check HKLM\SOFTWARE\Microsoft\Windows Sandbox\Persisted\ — the registry key for DeletePendingStorageId
  may appear, indicating the storage was attempted
  - IsDeveloperFunctionalityEnabled was also found in WindowsSandbox.exe — if the above doesn't work, that may be a
  secondary gate (Developer Mode in Windows Settings may need to be on)
  - RS5_EnableNoPersistenceVhd is a feature flag name — if it's enabled via RtlQueryFeatureConfiguration, it would block
   the VHDX. This would need a feature flag override if it's the blocker.

The issue i have is that this Persisted key is not created. So this means that there is still some policy issue. If anybody has claude code you can give it this post and ask claude to look into it. Maybe it can find what the correct policy is.
