### ISSUE TITLE
Add links to execution policy modification to the readme

### ISSUE THREAD

**Issue by fowie** [microsoft/Windows-Sandbox-Utilities#5]
Many users will probably get the error that the ps1 isn't digitally signed (unless they've already relaxed their execution policy).  It would be a good idea to have a section outlining how to change that (and the repercussions of doing so) in the readme.

**Comment by brasmith-ms** [comment]
Does this not accomplish that for you?
`Powershell.exe -ExecutionPolicy Bypass -File .\install_folding_sandbox_on_host.ps1`
Seems to work fine for me, but if it doesn't for you let me know. The 'Running the Sample' section of the README in the folding directory describes this.

**Comment by fowie** [comment]
Yep, that works.  Sorry, must have skimmed over that line.
