### ISSUE TITLE
NoRestart specified on machine causes script to fail

### ISSUE THREAD

**Issue by fowie** [microsoft/Windows-Sandbox-Utilities#6]
Testing on my home PC, I have NoRestart specified (not sure where?) so the machine didn't reboot after installing Windows Sandbox, which made the start-process line fail:
` 
Verifying that virtualization is enabled in BIOS...
Checking to see if Windows Sandbox is already installed...
Windows Sandbox is not installed, attempting to install it (may require reboot)...
WARNING: Restart is suppressed because NoRestart is specified.
Please reboot to finish installing Windows Sandbox, then re-run this script...
Checking for latest version of foldingathome...
Using FAH v7.5.
Downloading latest folding executable: C:\Users\spenc\fah_conf\folding_installer.exe
Saving to C:\Users\spenc\fah_conf\folding_installer.exe...
Creating init command...
Saved Folding@Home configuration file to C:\Users\spenc\fah_conf\fah_sandbox_conf.xml

    Directory: C:\Users\spenc\fah_conf

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/26/2020   8:53 AM              0 fah_sandbox_conf.xml
Creating init command...
Saved logon script to C:\Users\spenc\fah_conf\init.cmd, this will be run upon starting Sandbox.
-a----        3/26/2020   8:53 AM              0 init.cmd
Creating sandbox configuration file to C:\Users\spenc\fah_conf\fah_sandbox.wsb
-a----        3/26/2020   8:53 AM              0 fah_sandbox.wsb
Starting sandbox...
Start-Process : This command cannot be run due to the error: The system cannot find the file specified.
At G:\GIT\Windows-Sandbox-Utilities\Folding In Sandbox\install_folding_sandbox_on_host.ps1:108 char:1
+ Start-Process 'C:\WINDOWS\system32\WindowsSandbox.exe' -ArgumentList  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

`

**Comment by sebassem** [comment]
Added a pull request to exit the script if reboot is required to avoid getting this type of errors

**Comment by pbozzay** [comment]
PR approved; thank you! Closing.
