### ISSUE TITLE
Any reason not to set power to high?

### ISSUE THREAD

**Issue by fowie** [microsoft/Windows-Sandbox-Utilities#8]
Config file currently leaves processing power at default, "medium".  Since it's a sandbox, is there any reason not to set 
`
  <core-priority v="low"/>
`
?  I'm assuming that would allow it to run a little more often in the sandbox, but since the sandbox itself is standard-priority, it shouldn't adversely impact the host OS

**Comment by brasmith-ms** [comment]
I think that's totally reasonable. The point of running it in Sandbox is really to give it it's own dedicated environment, so mind as well make the most of what's available to it.

I'll make a PR for it. Setting the core-priority to low, and power to full? May play around with the priority and CPU usage settings as well.

**Comment by brasmith-ms** [comment]
#11 has been merged in, this should address the topic here.
